import type {
  HeroDocument,
  BentoCardDocument,
  ProjectDocument,
  TestimonialDocument,
  ClientDocument,
  ExperienceDocument,
  PhaseDocument,
  NavigationDocument,
  CtaDocument,
  FooterDocument,
  SocialLinkDocument,
  SeoDocument,
  AssistantDocument,
  CloudflareSettingsDocument,
  PublicPortfolioProjection,
} from "@/types/portfolio";
import type { LegalDocument } from "@/types/legal";

export const SEED_HERO: HeroDocument = {
  id: "hero_main",
  eyebrow: "Production Software Engineer · Full Stack & Systems",
  headingWords: "Architecting Scalable Systems & High-Performance Software",
  description: "I'm Gaurav Patil — a Production Software Engineer building high-throughput web architectures, native Rust & Tauri desktop applications, and scalable cloud backends with Next.js, Firebase/Firestore, and Redis.",
  ctaTitle: "Explore My Projects",
  ctaLink: "#projects",
  scrollText: "Scroll Down",
  isPublished: true,
  updatedAt: new Date().toISOString(),
  version: 1,
};

export const SEED_CARDS: BentoCardDocument[] = [
  {
    id: "card_01",
    slotIndex: 1,
    cardType: "collaboration",
    gridSpanVariant: "span_wide",
    visualLayout: "image_bottom",
    title: "I prioritize client collaboration, fostering open communication",
    description: "",
    img: "/b1.webp",
    spareImg: "",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "card_02",
    slotIndex: 2,
    cardType: "globe_timezone",
    gridSpanVariant: "span_default",
    visualLayout: "globe_canvas",
    title: "I'm very flexible with time zone communications",
    description: "",
    img: "",
    spareImg: "",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "card_03",
    slotIndex: 3,
    cardType: "tech_stack",
    gridSpanVariant: "span_default",
    visualLayout: "tech_pills",
    title: "My tech stack",
    description: "I constantly try to improve",
    techStackLeft: ["Next.js 16", "React 19", "TypeScript", "WebRTC"],
    techStackRight: ["Rust & Tauri", "TailwindCSS", "Node.js", "Firestore"],
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "card_04",
    slotIndex: 4,
    cardType: "passion",
    gridSpanVariant: "span_default",
    visualLayout: "image_bottom",
    title: "Tech enthusiast with a passion for development.",
    description: "",
    img: "/b4.svg",
    spareImg: "/grid.webp",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "card_05",
    slotIndex: 5,
    cardType: "current_project",
    gridSpanVariant: "span_wide",
    visualLayout: "image_right",
    title: "Software Engineer in office by week; building full-stack platforms & mail automation on weekends.",
    description: "The Inside Scoop · Active Workflow",
    img: "/b5.webp",
    spareImg: "/grid.webp",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "card_06",
    slotIndex: 6,
    cardType: "contact_cta",
    gridSpanVariant: "span_default",
    visualLayout: "centered_text",
    title: "Do you want to start a project together?",
    description: "",
    ctaEmail: "hello@gauravpatil.site",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_PROJECTS: ProjectDocument[] = [
  {
    id: "proj_01",
    order: 1,
    title: "Send2Me — Secure P2P File Transfer",
    slug: "send2me-p2p-file-transfer",
    description: "Direct peer-to-peer file transfers up to 10GB with zero cloud storage, complete privacy, and native desktop apps.",
    coverImageStoragePath: "/projects/send2me/cover.webp",
    coverImage: "/projects/send2me/cover.webp",
    images: [
      "/projects/send2me/cover.webp",
      "/projects/send2me/dashboard.webp",
      "/projects/send2me/features.webp",
      "/projects/send2me/mobile.webp",
    ],
    iconLists: [
      "/re.svg",
      "/next.svg",
      "/webrtc.svg",
      "/rust.svg",
      "/tauri.svg",
      "/tail.svg",
      "/firebase.svg",
    ],
    liveUrl: "https://www.send2me.site/",
    githubUrl: "https://github.com/AspiringWebGaurav/sendme.alt",
    desktopGithubUrl: "https://github.com/AspiringWebGaurav/send2me-rust-app",
    licenseStatus: "Open Source (MIT) · Web & Desktop",
    contractStatus: "Client Contract & Independent IP",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "proj_02",
    order: 2,
    title: "Switchyy — Real-Time App Mode Control",
    slug: "switchyy-mode-control",
    description: "Instant Live and Maintenance mode control for web apps without redeployments or server restarts.",
    coverImageStoragePath: "/projects/switchyy/cover.webp",
    coverImage: "/projects/switchyy/cover.webp",
    images: [
      "/projects/switchyy/cover.webp",
      "/projects/switchyy/dashboard.webp",
      "/projects/switchyy/features.webp",
      "/projects/switchyy/mobile.webp",
    ],
    iconLists: [
      "/next.svg",
      "/re.svg",
      "/ts.svg",
      "/tail.svg",
      "/cloud.svg",
    ],
    liveUrl: "https://switchyy.eu.cc/",
    docsUrl: "https://switchyy.eu.cc/docs",
    githubUrl: "https://github.com/AspiringWebGaurav/switchy",
    licenseStatus: "Commercial SaaS · Proprietary IP",
    contractStatus: "Client Contract Signed & Production SaaS Terms",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "proj_03",
    order: 3,
    title: "DareToSend — Anonymous Feedback Platform",
    slug: "daretosend-anonymous-feedback",
    description: "A professional, moderation-first anonymous feedback platform built for honest insights without the noise.",
    coverImageStoragePath: "/projects/daretosend/cover.webp",
    coverImage: "/projects/daretosend/cover.webp",
    images: [
      "/projects/daretosend/cover.webp",
      "/projects/daretosend/dashboard.webp",
      "/projects/daretosend/features.webp",
      "/projects/daretosend/mobile.webp",
    ],
    iconLists: [
      "/next.svg",
      "/re.svg",
      "/ts.svg",
      "/tail.svg",
      "/firebase.svg",
      "/firestore.svg",
    ],
    liveUrl: "https://daretosend.eu.cc/",
    githubUrl: "https://github.com/AspiringWebGaurav/daretosend",
    licenseStatus: "Partial Open Source · Client Contract Signed",
    contractStatus: "Client Contract Signed & Commercial SaaS",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "proj_04",
    order: 4,
    title: "XURL — Modern Smart URL Shortener",
    slug: "xurl-smart-url-shortener",
    description: "Smart URL shortener with sub-millisecond edge redirects, custom branded aliases, real-time analytics, and abuse defense.",
    coverImageStoragePath: "/projects/xurl/cover.webp",
    coverImage: "/projects/xurl/cover.webp",
    images: [
      "/projects/xurl/cover.webp",
      "/projects/xurl/dashboard.webp",
      "/projects/xurl/features.webp",
      "/projects/xurl/mobile.webp",
    ],
    iconLists: [
      "/next.svg",
      "/re.svg",
      "/ts.svg",
      "/tail.svg",
      "/firebase.svg",
      "/firestore.svg",
      "/cloud.svg",
    ],
    liveUrl: "https://xurl.eu.cc/",
    docsUrl: "https://xurl.eu.cc/documentation/api",
    githubUrl: "https://github.com/AspiringWebGaurav/xurl",
    licenseStatus: "Partial Open Source · Client Contract Signed",
    contractStatus: "Client Contract Signed & Commercial SaaS",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "proj_05",
    order: 5,
    title: "GPMAS — Smart Mail Scheduling & Automation",
    slug: "gpmas-mail-automation",
    description: "Enterprise-grade email scheduling system with multi-provider routing, intelligent failover, transactional locking, and real-time delivery tracking.",
    coverImageStoragePath: "/projects/gpmas/cover.webp",
    coverImage: "/projects/gpmas/cover.webp",
    images: [
      "/projects/gpmas/cover.webp",
      "/projects/gpmas/dashboard.webp",
      "/projects/gpmas/features.webp",
      "/projects/gpmas/mobile.webp",
    ],
    iconLists: [
      "/next.svg",
      "/re.svg",
      "/ts.svg",
      "/tail.svg",
      "/firebase.svg",
      "/cloud.svg",
    ],
    liveUrl: "https://gpmas.eu.cc/",
    githubUrl: "https://github.com/AspiringWebGaurav/Gauravs-Personal-Mail-Automation-System",
    licenseStatus: "Proprietary Automation Engine · Commercial SaaS",
    contractStatus: "Client Contract Signed & Production SLA",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "proj_06",
    order: 6,
    title: "GMP — Enterprise Operations & Management Panel",
    slug: "gmp-enterprise-portal",
    description: "Professional management dashboard for tracking tasks, telemetry, time analytics, and role-based access control with Google OAuth.",
    coverImageStoragePath: "/projects/gmp/cover.webp",
    coverImage: "/projects/gmp/cover.webp",
    images: [
      "/projects/gmp/cover.webp",
      "/projects/gmp/dashboard.webp",
      "/projects/gmp/features.webp",
      "/projects/gmp/mobile.webp",
    ],
    iconLists: [
      "/next.svg",
      "/re.svg",
      "/ts.svg",
      "/tail.svg",
      "/cloud.svg",
    ],
    liveUrl: "https://gauravmanagementportal.eu.cc/",
    githubUrl: "https://github.com/AspiringWebGaurav/GMP",
    licenseStatus: "Commercial ERP · Client Contract Signed",
    contractStatus: "Client Contract Signed & Active Maintenance",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "proj_07",
    order: 7,
    title: "GPDrive — Secure Personal Cloud Storage",
    slug: "gpdrive-cloud-storage",
    description: "High-performance cloud storage engine with Google OAuth session recovery, fast multipart uploads, private shareable links, and state recovery.",
    coverImageStoragePath: "/projects/gpdrive/cover.webp",
    coverImage: "/projects/gpdrive/cover.webp",
    images: [
      "/projects/gpdrive/cover.webp",
      "/projects/gpdrive/dashboard.webp",
      "/projects/gpdrive/features.webp",
      "/projects/gpdrive/mobile.webp",
    ],
    iconLists: [
      "/next.svg",
      "/re.svg",
      "/ts.svg",
      "/tail.svg",
      "/firebase.svg",
      "/firestore.svg",
    ],
    liveUrl: "https://gpdrive.eu.cc/",
    githubUrl: "https://github.com/AspiringWebGaurav/gauravs-personal-drive",
    licenseStatus: "Private Cloud Infrastructure · Proprietary",
    contractStatus: "Client Contract Signed & Private Cloud Agreement",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "proj_08",
    order: 8,
    title: "MyFit — Intelligent Workout & Fitness Suite",
    slug: "myfit-fitness-tracker",
    description: "Cross-platform fitness and workout tracker with progress telemetry, exercise builders, consistency heatmaps, and full desktop shell parity.",
    coverImageStoragePath: "/projects/myfit/cover.webp",
    coverImage: "/projects/myfit/cover.webp",
    images: [
      "/projects/myfit/cover.webp",
      "/projects/myfit/dashboard.webp",
      "/projects/myfit/features.webp",
      "/projects/myfit/mobile.webp",
    ],
    iconLists: [
      "/next.svg",
      "/re.svg",
      "/ts.svg",
      "/rust.svg",
      "/tauri.svg",
      "/tail.svg",
    ],
    liveUrl: "https://myfit.eu.cc/",
    githubUrl: "https://github.com/AspiringWebGaurav/MYFIT",
    licenseStatus: "Hybrid Mobile/Web SaaS · Client Contract Signed",
    contractStatus: "Client Contract Signed & Commercial Licensing",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "proj_09",
    order: 9,
    title: "GPNotes — Real-Time Encrypted Knowledge Workspace",
    slug: "gpnotes-encrypted-notes",
    description: "Enterprise-grade personal knowledge base with end-to-end encryption, markdown syncing, collaborative boards, and instant search.",
    coverImageStoragePath: "/projects/gpnotes/cover.webp",
    coverImage: "/projects/gpnotes/cover.webp",
    images: [
      "/projects/gpnotes/cover.webp",
      "/projects/gpnotes/dashboard.webp",
      "/projects/gpnotes/features.webp",
      "/projects/gpnotes/mobile.webp",
    ],
    iconLists: [
      "/next.svg",
      "/re.svg",
      "/ts.svg",
      "/tail.svg",
      "/firebase.svg",
      "/firestore.svg",
    ],
    liveUrl: "https://gpnotes.eu.cc/",
    githubUrl: "https://github.com/AspiringWebGaurav/gaurav-personal-notes",
    licenseStatus: "Partial Open Source · Client Agreement",
    contractStatus: "Client Contract Signed & Enterprise Support",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "proj_10",
    order: 10,
    title: "BGMI ID — Gaming Identity & Unicode Stylist",
    slug: "bgmiid-gaming-identity",
    description: "High-traffic gaming name stylist with 7 Unicode typography generators, 29+ game-compliant symbols, and real-time character limit validation.",
    coverImageStoragePath: "/projects/bgmiid/cover.webp",
    coverImage: "/projects/bgmiid/cover.webp",
    images: [
      "/projects/bgmiid/cover.webp",
      "/projects/bgmiid/dashboard.webp",
      "/projects/bgmiid/features.webp",
      "/projects/bgmiid/mobile.webp",
    ],
    iconLists: [
      "/re.svg",
      "/next.svg",
      "/ts.svg",
      "/tail.svg",
    ],
    liveUrl: "https://bgmiid.eu.cc/",
    githubUrl: "https://github.com/AspiringWebGaurav/bgmiid",
    licenseStatus: "Public Web Utility · 100% Free & Open",
    contractStatus: "Independent Commercial IP & Client Contract",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "proj_11",
    order: 11,
    title: "Gaurav Workspace — Recruiter Context & Launchpad",
    slug: "gauravwork-developer-workspace",
    description: "Lightning-fast executive overview providing instant resume access, live case study indexing, and interactive VibeCoding beta environment.",
    coverImageStoragePath: "/projects/gauravwork/cover.webp",
    coverImage: "/projects/gauravwork/cover.webp",
    images: [
      "/projects/gauravwork/cover.webp",
      "/projects/gauravwork/dashboard.webp",
      "/projects/gauravwork/features.webp",
      "/projects/gauravwork/mobile.webp",
    ],
    iconLists: [
      "/next.svg",
      "/re.svg",
      "/ts.svg",
      "/tail.svg",
    ],
    liveUrl: "https://gauravwork.eu.cc/",
    githubUrl: "https://github.com/AspiringWebGaurav/Gauravs-WorkSpace",
    licenseStatus: "Personal Developer Hub · MIT License",
    contractStatus: "Independent Commercial IP & Verified Portfolio",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "proj_12",
    order: 12,
    title: "Gaurav Builds — Software Architecture & Release Index",
    slug: "gauravbuilds-artifacts-hub",
    description: "Enterprise software architecture portfolio, technical execution analysis, and multi-platform build distribution engine.",
    coverImageStoragePath: "/projects/gauravbuilds/cover.webp",
    coverImage: "/projects/gauravbuilds/cover.webp",
    images: [
      "/projects/gauravbuilds/cover.webp",
      "/projects/gauravbuilds/dashboard.webp",
      "/projects/gauravbuilds/features.webp",
      "/projects/gauravbuilds/mobile.webp",
    ],
    iconLists: [
      "/next.svg",
      "/re.svg",
      "/ts.svg",
      "/tail.svg",
      "/cloud.svg",
    ],
    liveUrl: "https://gauravbuilds.eu.cc/",
    githubUrl: "https://github.com/AspiringWebGaurav/gaurav-builds",
    licenseStatus: "Software Portfolio & Artifact Distribution",
    contractStatus: "Client Contract Signed & Cloud Infrastructure",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "proj_13",
    order: 13,
    title: "Gaurav Watch — Precision Chronograph & Time Dashboard",
    slug: "gauravwatch-precision-chronograph",
    description: "Zero-distraction digital desk clock and productivity companion with sun/moon astronomical cycles, battery telemetry, and sub-millisecond sync.",
    coverImageStoragePath: "/projects/gauravwatch/cover.webp",
    coverImage: "/projects/gauravwatch/cover.webp",
    images: [
      "/projects/gauravwatch/cover.webp",
      "/projects/gauravwatch/dashboard.webp",
      "/projects/gauravwatch/features.webp",
      "/projects/gauravwatch/mobile.webp",
    ],
    iconLists: [
      "/re.svg",
      "/next.svg",
      "/ts.svg",
      "/tail.svg",
    ],
    liveUrl: "https://gauravwatch.eu.cc/",
    githubUrl: "https://github.com/AspiringWebGaurav/clock",
    licenseStatus: "Open Source (MIT) · Minimalist Productivity Tool",
    contractStatus: "Independent Commercial IP & Client Contract",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "proj_14",
    order: 14,
    title: "Connect Gaurav — Unified Developer Social Hub",
    slug: "connectgaurav-developer-hub",
    description: "Unified developer presence platform, appointment scheduling hub, and direct executive connection gateway.",
    coverImageStoragePath: "/projects/connectgaurav/cover.webp",
    coverImage: "/projects/connectgaurav/cover.webp",
    images: [
      "/projects/connectgaurav/cover.webp",
      "/projects/connectgaurav/dashboard.webp",
      "/projects/connectgaurav/features.webp",
      "/projects/connectgaurav/mobile.webp",
    ],
    iconLists: [
      "/next.svg",
      "/re.svg",
      "/ts.svg",
      "/tail.svg",
    ],
    liveUrl: "https://connectgaurav.eu.cc/",
    githubUrl: "https://github.com/AspiringWebGaurav/connectgaurav",
    licenseStatus: "Enterprise Workspace · Client Contract Signed",
    contractStatus: "Client Contract Signed & Dedicated SLA",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_TESTIMONIALS: TestimonialDocument[] = [
  {
    id: "test_01",
    order: 1,
    quote: "Gaurav engineered a robust client portal and digital workflow system for Vatvruksha Engineering. His technical precision, proactive communication, and ability to translate industrial requirements into an intuitive, high-performance web interface made a substantial impact on our operational efficiency.",
    name: "Saurabh Patil",
    role: "Founder & Technical Director",
    company: "Vatvruksha Engineering",
    avatarStoragePath: "/testimonials/saurabh-patil.png",
    avatarUrl: "/testimonials/saurabh-patil.png",
    socialUrl: "https://www.facebook.com/search/top?q=saurabh%20ravsaheb%20patil",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "test_02",
    order: 2,
    quote: "Partnering with Gaurav gave Gurudatta Group of Services a modern, high-converting digital platform and automated service tracking workflows. He took full architectural ownership from frontend fluidity to backend data integrity with zero compromise on quality and delivery timelines.",
    name: "Akash Ekshinge",
    role: "Managing Director",
    company: "Gurudatta Group of Services",
    avatarStoragePath: "/testimonials/akash-ekshinge.png",
    avatarUrl: "/testimonials/akash-ekshinge.png",
    socialUrl: "https://www.facebook.com/akash.ekshinge",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "test_03",
    order: 3,
    quote: "Gaurav modernized our digital presence with a lightning-fast responsive web app, digital menu architecture, and table reservation flows for Palash Resto and FineDine. Our guests love the fluid UX, and our operational coordination has never been smoother.",
    name: "Shubham Patil",
    role: "Managing Partner",
    company: "Palash Resto and FineDine",
    avatarStoragePath: "/testimonials/shubham-patil.png",
    avatarUrl: "/testimonials/shubham-patil.png",
    socialUrl: "https://www.facebook.com/palashrestaurant",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "test_04",
    order: 4,
    quote: "Gaurav developed our comprehensive enterprise operations management portal (GMP) under strict NDA terms. He implemented granular role-based access control, automated audit logs, and unified operational analytics. Flawless security, zero data leaks, and exceptional code quality.",
    name: "Anonymous Client",
    role: "Operations Director",
    company: "Enterprise ERP Management · Client Contract Signed (Anonymous per NDA)",
    avatarStoragePath: "/profile.webp",
    avatarUrl: "/profile.webp",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "test_05",
    order: 5,
    quote: "Contracted Gaurav to deploy and customize the XURL edge shortener engine for our marketing campaign infrastructure. Handles millions of requests with sub-millisecond edge redirects and real-time geo-analytics. Exceptional engineering discipline throughout.",
    name: "Confidential Client",
    role: "Head of Growth & Infrastructure",
    company: "High-Volume Marketing SaaS · Client Contract Signed (Identity Protected)",
    avatarStoragePath: "/profile.webp",
    avatarUrl: "/profile.webp",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "test_06",
    order: 6,
    quote: "Integrated Switchyy into our mission-critical deployment workflow. Gaurav's zero-restart maintenance mode toggle eliminated deployment customer friction and guaranteed 99.99% uptime compliance across our staging and production servers.",
    name: "Anonymous Client",
    role: "Lead DevOps Engineer",
    company: "FinTech Web Infrastructure · Client Contract Signed (Anonymous per NDA)",
    avatarStoragePath: "/profile.webp",
    avatarUrl: "/profile.webp",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "test_07",
    order: 7,
    quote: "Commissioned a bespoke internal deployment of DareToSend for our organization. The end-to-end anonymity guarantees and automated moderation filters created an open, honest communication channel across our teams without corporate toxicity.",
    name: "Confidential Client",
    role: "People & Culture Lead",
    company: "Corporate Pulse Feedback · Client Contract Signed (Identity Protected)",
    avatarStoragePath: "/profile.webp",
    avatarUrl: "/profile.webp",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "test_08",
    order: 8,
    quote: "Gaurav engineered a private, client-side encrypted cloud storage solution with chunked uploads and signed authorization tokens. Outstanding attention to data privacy, zero-leak storage architecture, and stringent security benchmarks.",
    name: "Anonymous Client",
    role: "Compliance & Security Officer",
    company: "Private Cloud Storage · Client Contract Signed (Anonymous per NDA)",
    avatarStoragePath: "/profile.webp",
    avatarUrl: "/profile.webp",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "test_09",
    order: 9,
    quote: "Contracted Gaurav to overhaul our transactional email routing and dispatch infrastructure. His dual-relay failover architecture and automated verification webhooks reduced delivery drop-offs to absolute zero with instant latency.",
    name: "Confidential Client",
    role: "Marketing Operations Specialist",
    company: "Transactional Messaging Relay · Client Contract Signed (NDA Retained)",
    avatarStoragePath: "/profile.webp",
    avatarUrl: "/profile.webp",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "test_10",
    order: 10,
    quote: "Gaurav delivered a high-concurrency player ID verification and tournament bracket management platform. Handled severe traffic spikes during registrations seamlessly without a single hitch or database bottleneck.",
    name: "Anonymous Client",
    role: "Esports Tournament Coordinator",
    company: "Gaming & Community Verification · Client Contract Signed (Anonymous)",
    avatarStoragePath: "/profile.webp",
    avatarUrl: "/profile.webp",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "test_11",
    order: 11,
    quote: "Bespoke member tracking and workout logging portal developed on schedule. The desktop-mobile parity, fluid offline state hydration, and clean UI resulted in a 40% jump in member app engagement across our clubs.",
    name: "Confidential Client",
    role: "Fitness Brand General Manager",
    company: "Health & Member Management · Client Contract Signed (Identity Protected)",
    avatarStoragePath: "/profile.webp",
    avatarUrl: "/profile.webp",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "test_12",
    order: 12,
    quote: "Gaurav built an ultra-fast, zero-layout-shift markdown knowledge repository with keyboard shortcuts and instant client-side indexing. One of the cleanest, most responsive developer tools our research team uses daily.",
    name: "Anonymous Client",
    role: "Research & Documentation Lead",
    company: "Knowledge Management Workspace · Client Contract Signed (Anonymous)",
    avatarStoragePath: "/profile.webp",
    avatarUrl: "/profile.webp",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "test_13",
    order: 13,
    quote: "Contracted Gaurav to design and build our synchronized team workspace with real-time state hydration, project roadmaps, and secure access gates. Highly disciplined developer who writes defensive, scalable, production-ready code.",
    name: "Confidential Client",
    role: "Remote Product Lead",
    company: "Distributed Workspace Platform · Client Contract Signed (NDA Retained)",
    avatarStoragePath: "/profile.webp",
    avatarUrl: "/profile.webp",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_CLIENTS: ClientDocument[] = [
  {
    id: "client_01",
    order: 1,
    name: "Vatvruksha Engineering",
    iconStoragePath: "/clients/vatvruksha-icon.svg",
    iconUrl: "/clients/vatvruksha-icon.svg",
    nameImgStoragePath: "/clients/vatvruksha-name.svg",
    nameImgUrl: "/clients/vatvruksha-name.svg",
    websiteUrl: "https://www.facebook.com/search/top?q=saurabh%20ravsaheb%20patil",
    logoWidth: 160,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "client_02",
    order: 2,
    name: "Gurudatta Group of Services",
    iconStoragePath: "/clients/gurudatta-icon.svg",
    iconUrl: "/clients/gurudatta-icon.svg",
    nameImgStoragePath: "/clients/gurudatta-name.svg",
    nameImgUrl: "/clients/gurudatta-name.svg",
    websiteUrl: "https://www.facebook.com/akash.ekshinge",
    logoWidth: 170,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "client_03",
    order: 3,
    name: "Palash Resto & FineDine",
    iconStoragePath: "/clients/palash-icon.svg",
    iconUrl: "/clients/palash-icon.svg",
    nameImgStoragePath: "/clients/palash-name.svg",
    nameImgUrl: "/clients/palash-name.svg",
    websiteUrl: "https://www.facebook.com/palashrestaurant",
    logoWidth: 160,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "client_04",
    order: 4,
    name: "Stealth FinTech Venture",
    iconStoragePath: "/clients/fintech-icon.svg",
    iconUrl: "/clients/fintech-icon.svg",
    nameImgStoragePath: "/clients/fintech-name.svg",
    nameImgUrl: "/clients/fintech-name.svg",
    logoWidth: 160,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "client_05",
    order: 5,
    name: "Enterprise Cloud SaaS",
    iconStoragePath: "/clients/saas-icon.svg",
    iconUrl: "/clients/saas-icon.svg",
    nameImgStoragePath: "/clients/saas-name.svg",
    nameImgUrl: "/clients/saas-name.svg",
    logoWidth: 160,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_EXPERIENCE: ExperienceDocument[] = [
  {
    id: "exp_01",
    order: 1,
    title: "Full Stack Web Trainee",
    description: "Graduated after 1200+ hours of rigorous full-stack software development training, mastering MERN stack, data structures, and collaborative builds.",
    company: "Masai School",
    period: "2021 - 2022",
    thumbnailStoragePath: "/exp1.svg",
    thumbnailUrl: "/exp1.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "exp_02",
    order: 2,
    title: "Software Engineer",
    description: "Engineering enterprise-grade web platforms using React, Next.js, and TypeScript, delivering robust user interfaces, clean architecture, and scalable APIs.",
    company: "NeoSOFT",
    period: "2022 - Present",
    thumbnailStoragePath: "/exp2.svg",
    thumbnailUrl: "/exp2.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "exp_03",
    order: 3,
    title: "Independent Contractor & Freelancer",
    description: "Delivering bespoke client solutions and full-stack web applications on weekends under strict contractual terms, conditions, and IP governance.",
    company: "Weekend Contracting (Sat - Sun)",
    period: "2023 - Present",
    thumbnailStoragePath: "/exp3.svg",
    thumbnailUrl: "/exp3.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "exp_04",
    order: 4,
    title: "Open Source & Product Engineer",
    description: "Architecting and publishing production-grade SaaS products and developer platforms (Send2Me, Switchyy, DareToSend, XURL) with Next.js, Rust, and WebRTC.",
    company: "Independent & Open Source",
    period: "2024 - Present",
    thumbnailStoragePath: "/exp4.svg",
    thumbnailUrl: "/exp4.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_PHASES: PhaseDocument[] = [
  {
    id: "phase_01",
    order: 1,
    phaseBadge: "Phase 1",
    title: "Architecture, Docs & Contract Governance",
    description:
      "Every engagement begins with in-depth system design research, comprehensive technical documentation, and clear terms & conditions. I define exact data models, API boundaries, and IP terms to ensure complete alignment and legal clarity before writing code.",
    themeColor: "emerald",
    animationSpeed: 5.1,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "phase_02",
    order: 2,
    phaseBadge: "Phase 2",
    title: "Modular Engineering & Milestone Delivery",
    description:
      "I engineer solutions using clean 4-tier pipelines, type-safe TypeScript, and modular design systems. Development progresses through scheduled milestone checkpoints and transparent demos, ensuring predictable delivery and rigorous code quality.",
    themeColor: "pink",
    animationSpeed: 3,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "phase_03",
    order: 3,
    phaseBadge: "Phase 3",
    title: "Security Hardening & Production Launch",
    description:
      "Before release, the system undergoes end-to-end type verification, security hardening, edge rate-limiting, and performance benchmarking. I execute zero-downtime production rollouts accompanied by complete API docs, deployment guides, and post-launch stability.",
    themeColor: "sky",
    animationSpeed: 3,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_NAVIGATION: NavigationDocument = {
  id: "nav_main",
  items: [
    { id: "nav_about", name: "About", link: "#about", order: 1, isVisible: true },
    { id: "nav_projects", name: "Projects", link: "#projects", order: 2, isVisible: true },
    { id: "nav_testimonials", name: "Testimonials", link: "#testimonials", order: 3, isVisible: true },
    { id: "nav_contact", name: "Contact", link: "#contact", order: 4, isVisible: true },
  ],
  updatedAt: new Date().toISOString(),
  version: 1,
};

export const SEED_CTA: CtaDocument = {
  id: "cta_main",
  headingPrefix: "Ready to take ",
  headingHighlight: "your",
  headingSuffix: " digital presence to the next level?",
  description: "Reach out to me today and let's discuss how I can help you achieve your goals.",
  buttonText: "Let's get in touch",
  isEnabled: true,
  updatedAt: new Date().toISOString(),
  version: 1,
};

export const SEED_FOOTER: FooterDocument = {
  id: "footer_main",
  copyrightName: "Gaurav Patil",
  termsUrl: "/terms",
  privacyUrl: "/privacy",
  updatedAt: new Date().toISOString(),
  version: 1,
};

export const SEED_SOCIAL_LINKS: SocialLinkDocument[] = [
  {
    id: "soc_01",
    order: 1,
    platform: "GitHub",
    url: "https://github.com/AspiringWebGaurav",
    iconType: "preset",
    presetName: "github",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_SEO: SeoDocument = {
  id: "seo_main",
  title: "Gaurav Patil — Full Stack Developer & Software Engineer",
  description:
    "Official portfolio of Gaurav Patil, a Full Stack Developer & Software Engineer based in India specializing in Next.js, React, TypeScript, and modern scalable web architecture.",
  canonicalUrl: "https://gauravpatil.site",
  ogImageStoragePath: "",
  ogImageUrl: "",
  keywords: [
    "Gaurav Patil",
    "Gaurav Patil developer",
    "Gaurav Patil full stack developer",
    "Gaurav Patil software developer",
    "Gaurav Patil portfolio",
    "Gaurav Patil India",
    "Full Stack Developer",
    "Software Engineer",
    "Next.js",
    "React",
    "TypeScript",
    "Tailwind CSS",
  ],
  author: "Gaurav Patil",
  twitterHandle: "@gauravpatil",
  updatedAt: new Date().toISOString(),
  version: 1,
};

export const SEED_ASSISTANT: AssistantDocument = {
  id: "assistant_main",
  isEnabled: true,
  assistantName: "Gaurav Assistant",
  avatarUrl: "",
  positionMode: "fixed",
  updatedAt: new Date().toISOString(),
  version: 1,
};

export const SEED_CLOUDFLARE: CloudflareSettingsDocument = {
  id: "cloudflare_main",
  isSimulatedDowntime: false,
  siteKey: "0x4AAAAAAEilFWDvwBZ3NPSK",
  maxRetryAttempts: 2,
  circuitBreakerEnabled: true,
  fallbackEmailGateway: "no-reply@gauravpatil.site",
  updatedAt: new Date().toISOString(),
  version: 1,
};

export const SEED_PORTFOLIO_PROJECTION: PublicPortfolioProjection = {
  navigation: SEED_NAVIGATION.items,
  hero: SEED_HERO,
  cards: SEED_CARDS,
  projects: SEED_PROJECTS,
  testimonials: SEED_TESTIMONIALS,
  clients: SEED_CLIENTS,
  experience: SEED_EXPERIENCE,
  phases: SEED_PHASES,
  cta: SEED_CTA,
  footer: SEED_FOOTER,
  socialLinks: SEED_SOCIAL_LINKS,
  seo: SEED_SEO,
  assistant: SEED_ASSISTANT,
  cloudflare: SEED_CLOUDFLARE,
};

export const SEED_TERMS_DOCUMENT: LegalDocument = {
  id: "terms_active",
  docType: "TERMS",
  title: "Terms of Service",
  publishedVersion: "1.0.0",
  publishedAt: "2026-09-09T00:00:00.000Z",
  effectiveDate: "January 1, 2026",
  lastUpdatedDate: "September 9, 2026",
  jurisdiction: "Standard Global",
  version: 1,
  updatedAt: new Date().toISOString(),
  sections: [
    {
      id: "acceptance",
      heading: "1. Acceptance of Terms & Accessibility Commitment",
      filterMode: "all",
      order: 1,
      contentMarkdown: "By accessing, browsing, submitting inquiries, using authenticated services, or otherwise interacting with **Gaurav Portfolio**, you acknowledge and agree to be bound by these Terms of Service and all applicable policies. This platform commits to a strict **Mobile-First 10/10 Production Standard**, ensuring zero horizontal overflow, fluid typography, touch-ergonomic 44px hit targets, accessible reduced-motion fallbacks, and single-view contact workflows across all modern smartphones, tablets, and desktop workstations. If you do not agree with any provision, you may discontinue viewing or utilizing this platform.",
    },
    {
      id: "anonymity",
      heading: "2. Right to Confidential & Anonymous Communication",
      filterMode: "contact",
      order: 2,
      contentMarkdown: "Users and prospective partners are welcome to initiate contact anonymously:\n\n- **Confidential Inquiries:** Submitting an inquiry with the default \"Anonymous / Confidential\" role is fully permitted and legally respected as preliminary communication.\n- **Non-Disclosure Friendly:** Mutual non-disclosure agreements (NDAs) can be executed upon request prior to exchanging proprietary project details.",
    },
    {
      id: "ip",
      heading: "3. Intellectual Property & Engineering Architecture",
      filterMode: "all",
      order: 3,
      contentMarkdown: "All original visual design systems, dark luxury glassmorphic layouts, Three.js 3D Globe implementations, and full-stack software architectures showcased on this platform are the intellectual property of **Gaurav Patil**. Client deliverables and bespoke software engineering codebases are transferred strictly per individual written engagement agreements upon milestone completion.",
    },
    {
      id: "abuse-mitigation",
      heading: "4. Automated Abuse Mitigation & Cloudflare Verification",
      filterMode: "contact",
      order: 4,
      contentMarkdown: "To maintain high uptime and system integrity, public mutation endpoints (such as the contact form) are protected by **Cloudflare Turnstile**. Automated scraping, malicious payload injection, bot spam, and denial-of-service attempts are strictly prohibited and actively mitigated.",
    },
    {
      id: "email-standards",
      heading: "5. Transactional Communication Standards & Mandatory Legal Update Announcements",
      filterMode: "contact",
      order: 5,
      contentMarkdown: "All transactional emails, contact receipts, security alerts, and mandatory policy notices are dispatched from the authenticated server domain `gauravpatil.site` via Brevo API. Official sender identities include `gaurav@gauravpatil.site` (direct professional connections and consulting agreements), `hello@gauravpatil.site` (general inquiries and auto-replies), `security@gauravpatil.site` (authentication alerts and audit logs), `help@gauravpatil.site` (support), and `no-reply@gauravpatil.site` (system OTPs and automated legal announcements). A strict zero-spam guarantee is maintained: submitted contact emails are never enrolled in promotional marketing sequences.\n\n### Mandatory Legal & Policy Update Announcement Notice\n\n- **Automatic Registration for Policy Updates:** Submitting an email address through any service of this portfolio — including Contact Form inquiries, Live Chat email OTP authentication, support requests, or direct communications — registers that address to receive mandatory policy, legal, and security announcements in accordance with your acceptance of use.\n- **Mandatory Non-Marketing Announcements:** When material updates are made to the public Terms of Service, Privacy Policy, or critical security procedures, automated informational notices are broadcast directly from `no-reply@gauravpatil.site` or `security@gauravpatil.site`. These communications are strictly non-commercial, transactional legal disclosures and contain zero marketing or promotional sequences.\n- **No Unsubscribe & Immunity from Automated Client-Level Unsubscribe:** Because legal update announcements are mandatory contractual disclosures required to maintain operational and legal transparency for all users who have interacted with Gaurav Portfolio or its authenticated services, **no unsubscribe or opt-out option is provided**. Even if automated email client features (such as Google/Gmail's automatic \"Unsubscribe\" header or client-level spam filters) are invoked, you acknowledge and agree that you will continue to receive mandatory legal, policy, and security notices as per this policy and your acceptance of use.",
    },
    {
      id: "assistant-terms",
      heading: "6. Personal Assistant (Beta) Operational Terms & AI Disclaimer",
      filterMode: "assistant",
      order: 6,
      contentMarkdown: "### Purpose & Scope of Gaurav Assistant & Live Chat\n\nThe Personal Assistant and Live Chat system are engineered to provide an interactive, personal communication channel with Gaurav Patil. It provides direct, automated insights into engineering benchmarks, architecture patterns, and project deliverables, while facilitating immediate 1-to-1 live communication.\n\n### Live Chat Real-Time Dispatch & Notification Architecture\n\nWhen you initiate a conversation through **Live Chat with Gaurav**, the backend operates a hybrid real-time communication pipeline:\n\n- **Active Online Streaming:** If Gaurav is actively online and connected to the session, incoming messages arrive instantly in real-time.\n- **Automated Inbox Dispatch:** If Gaurav is away or offline, the server instantaneously generates and dispatches an automated lead notification directly to Gaurav's private inbox containing your verified sender details and full message transcript with 1-click direct response routing.\n- **Single-Use 6-Digit Email Verification:** To eliminate spam and protect system resources, access to Live Chat requires a single-use 6-digit OTP code dispatched exclusively from `no-reply@gauravpatil.site`. Verification codes expire in 5 minutes.\n- **4-Hour Active Session Token:** Once verified, an encrypted session remains active for 4 hours. You may close and reopen the chat window anytime within this window without re-authenticating. Visitors may explicitly terminate their session at any time using the **Sign out** button in the top-right header.\n\n### Official Verified Senders & Support Pipeline\n\nAll communications, support tickets, and contact verification flows originate exclusively from the authenticated domain `gauravpatil.site`:\n\n- `gaurav@gauravpatil.site` — Direct professional inquiries, technical consulting proposals, and executive recruiter outreach.\n- `hello@gauravpatil.site` — General portfolio inquiries, recruiter outreach, and direct developer contact.\n- `help@gauravpatil.site` — Assistant technical support, bug reports, and portfolio navigation guidance.\n- `security@gauravpatil.site` — Security notifications, 2FA OTP codes, and vulnerability disclosure reports.\n- `no-reply@gauravpatil.site` — Automated Live Chat OTP passcodes, system receipts, and non-interactive alerts.\n\n### AI Accuracy Disclaimer & Acceptable Use\n\n- **Generative Limitations:** While tuned for accuracy, automated assistant responses may occasionally produce incomplete or summarized statements. Official portfolio source code and direct communication with Gaurav remain authoritative benchmarks.\n- **Acceptable Use:** Visitors agree not to attempt prompt-injections, reverse-engineer underlying system prompts, extract internal configuration, or send abusive payloads.\n- **Continuous Beta Evolution:** The assistant is under active development and may undergo live feature updates or brief maintenance windows without notice.",
    },
    {
      id: "whatsapp-terms",
      heading: "7. WhatsApp Recruiter & Visitor Communication Channel",
      filterMode: "whatsapp",
      order: 7,
      contentMarkdown: "Gaurav Portfolio provides an official Meta WhatsApp Business Cloud API integration allowing recruiters, hiring managers, and prospective clients to connect directly with Gaurav Patil. Use of this channel is subject to the following terms:\n\n- **Authorized Professional Scope:** This WhatsApp channel is exclusively intended for professional recruitment discussions, job opportunities, engineering inquiries, and technical collaboration proposals. Promotional spam, harassment, or unsolicited marketing is strictly prohibited.\n- **Message Quota & Anti-Spam Safeguards:** To prevent spam and protect direct communication channels, sessions are allocated up to 3 direct inquiry message slots. Messages are delivered instantaneously to Gaurav Patil in real time with 1-click email response triggers.\n- **Unsubscribe & Immediate Data Erasure:** You may opt out at any time by replying `STOP`. Replying STOP immediately unsubscribes your number and permanently erases your conversation history from the database (GDPR Right to Erasure). You can resume anytime by replying `START`.\n- **Data Portability & Self-Service Export:** Under GDPR Article 20, you retain full ownership of your conversation records. You can type `/exportmydata` anytime in WhatsApp to instantly receive a cryptographically signed ZIP archive with your complete records (links are strictly time-limited to 10 minutes for privacy).",
    },
    {
      id: "admin-governance",
      heading: "8. Administrative Subsystem Isolation & 2FA Governance",
      filterMode: "all",
      order: 8,
      contentMarkdown: "The administrative panel (`/admin/*`) is an isolated workspace strictly restricted to authorized Superadmins. Administrative access requires Google OAuth 2.0 PKCE, salted HMAC-SHA256 Two-Factor Authentication (OTP), and zero-lockout IP security verification. Administrative access and data operations are governed separately under the Administrator Terms of Service.",
    },
    {
      id: "liability",
      heading: "9. Limitation of Liability & Disclaimers",
      filterMode: "all",
      order: 9,
      contentMarkdown: "This website and its demonstrative artifacts are provided on an \"as is\" and \"as available\" basis. In no event shall Gaurav Patil be liable for indirect, incidental, or consequential damages resulting from the use of this website.",
    },
    {
      id: "legal-contact",
      heading: "10. Inquiries & Legal Notices",
      filterMode: "all",
      order: 10,
      contentMarkdown: "For contract proposals, bespoke engineering consulting, or professional engagement agreements:\n\n- **Direct Professional Line:** [gaurav@gauravpatil.site](mailto:gaurav@gauravpatil.site) *(Reserved strictly for professional proposals, consulting contracts, and executive recruiter correspondence)*\n- **General Inquiries & Notices:** [hello@gauravpatil.site](mailto:hello@gauravpatil.site)",
    },
  ],
};

export const SEED_PRIVACY_DOCUMENT: LegalDocument = {
  id: "privacy_active",
  docType: "PRIVACY",
  title: "Privacy Policy",
  publishedVersion: "1.0.0",
  publishedAt: "2026-09-09T00:00:00.000Z",
  effectiveDate: "January 1, 2026",
  lastUpdatedDate: "September 9, 2026",
  jurisdiction: "Privacy-First",
  version: 1,
  updatedAt: new Date().toISOString(),
  sections: [
    {
      id: "overview",
      heading: "1. Overview & Privacy-First Philosophy",
      filterMode: "all",
      order: 1,
      contentMarkdown: "Your privacy, autonomy, and security are non-negotiable. This Privacy Policy governs how data is handled across **Gaurav Portfolio**. The architecture operates on strict data minimization principles: only the minimum information necessary to facilitate professional communication is collected, with zero third-party data tracking, zero cookie profiling, and zero monetization of personal information.",
    },
    {
      id: "anonymity",
      heading: "2. Absolute Right to Anonymity & Confidential Inquiries",
      filterMode: "contact",
      order: 2,
      contentMarkdown: "Every visitor and prospective collaborator has the full, unrestricted right to maintain complete anonymity:\n\n- **Default Anonymous Role:** The contact form defaults to the \"Anonymous / Confidential\" identity to ensure no visitor is pressured into declaring a specific role.\n- **Pseudonyms & Private Relays:** You may submit inquiries using an alias, pseudonym, or privacy-relayed email address (such as Apple Relay or SimpleLogin).\n- **Zero Telemetry Correlation:** Inbound contact messages are strictly segregated from user-agent fingerprints and external analytics data.",
    },
    {
      id: "turnstile",
      heading: "3. Bot Mitigation & Ephemeral Cloudflare Turnstile Evaluation",
      filterMode: "contact",
      order: 3,
      contentMarkdown: "To protect public endpoints against automated spam and DDoS attacks, the system utilizes **Cloudflare Turnstile**:\n\n- **Cookie-Free Evaluation:** Turnstile evaluates browser telemetry ephemerally during submission without setting persistent cross-site tracking cookies.\n- **Server-Side Token Validation:** Tokens are validated instantaneously via server-to-server TLS calls and discarded immediately following verification.",
    },
    {
      id: "brevo",
      heading: "4. Transactional Communications & Brevo Delivery Gateway",
      filterMode: "contact",
      order: 4,
      contentMarkdown: "All transactional communications, verification passcodes, and mandatory legal announcements are routed through an enterprise Brevo server pipeline:\n\n- **Authenticated Domain:** Official communications originate strictly from the verified primary identity `gauravpatil.site`.\n- **Official Senders:**\n  - `hello@gauravpatil.site` (Direct contact & automated receipts)\n  - `security@gauravpatil.site` (Security alerts, authentication verification & push audit logs)\n  - `help@gauravpatil.site` (Support & assistance)\n  - `no-reply@gauravpatil.site` (System OTPs & mandatory legal update announcements)\n- **Strict Non-Marketing Standard:** Submitting an inquiry or authenticating will never enroll you in promotional campaigns or marketing distributions.\n\n### Mandatory Legal Update Broadcasts & Strict No-Unsubscribe Standard\n\nEmail addresses provided through Contact Form submissions, Assistant/Live Chat OTP authentication, or direct inquiries are retained securely in cloud databases. These addresses receive mandatory service announcements whenever the public Terms of Service or Privacy Policy are amended. Because these notices represent vital legal disclosures required for platform transparency and governance (and never commercial marketing), they do not include marketing unsubscribe links and cannot be opted out of, even through third-party automated email client features (such as Google/Gmail automatic 1-click unsubscribe headers).",
    },
    {
      id: "data-rights",
      heading: "5. Data Security, Storage & Deletion Rights",
      filterMode: "all",
      order: 5,
      contentMarkdown: "Inquiries are stored in encrypted cloud databases (Firebase Firestore / Realtime Database in region `asia-southeast1`) with atomic lead tracking. You retain the right under GDPR, CCPA, and international privacy standards to:\n\n- Request a copy of any communication history associated with your email.\n- Request permanent, atomic deletion of all submitted contact records and message drafts.",
    },
    {
      id: "assistant-privacy",
      heading: "6. Personal Assistant (Beta) & AI Safety Architecture",
      filterMode: "assistant",
      order: 6,
      contentMarkdown: "### Why Gaurav Assistant Was Created\n\nThe Personal Assistant was conceived and engineered as an **intelligent interactive portfolio navigator** designed to elevate how recruiters, hiring managers, engineering leaders, and potential clients explore Gaurav Patil's work. Instead of manually parsing static resume bullets, visitors can receive real-time answers concerning deep case studies, technical specializations, engineering philosophy, and live architectural demonstrations.\n\n### Custom Mail Domain Support & Verified Communication Channels\n\nAll visitor interactions, assistant support inquiries, and transactional communications are backed by a dedicated, enterprise-grade Brevo email delivery pipeline configured with strict **SPF, DKIM, and DMARC** authentication records. Official communication originating from this portfolio is bound to the primary authenticated domain `gauravpatil.site`:\n\n- `gaurav@gauravpatil.site` — Direct professional contact, engineering consulting engagements, and formal controller correspondence.\n- `hello@gauravpatil.site` — Direct portfolio contact, visitor inquiries, developer collaboration, and automated inquiry receipts.\n- `help@gauravpatil.site` — Assistant technical assistance, bug reports, user feedback, and portfolio navigation support.\n- `security@gauravpatil.site` — Security disclosures, vulnerability reports, 2FA OTP codes, and authentication alerts.\n- `no-reply@gauravpatil.site` — Non-interactive automated notifications, system passcodes, and security verifications only.\n\n### Live Chat Notification Privacy & 4-Hour Session Security\n\n- **Direct Message Routing:** When you send a message in Live Chat, it is streamed immediately if Gaurav is connected. When away, the automated system triggers an instantaneous notification email to Gaurav's personal inbox with your message transcript and 1-click reply routing.\n- **Zero Plaintext OTP Storage:** 6-digit verification codes are hashed using salted HMAC-SHA256 before storage and destroyed immediately upon successful authentication or after 5 minutes.\n- **Encrypted 4-Hour Session Token:** Verified sessions are stored in an encrypted `httpOnly`, `SameSite=Lax` cookie valid for 4 hours. You can close and return to the portfolio anytime during this period without re-verifying.\n- **1-Click Sign-Out & Detachment:** You may revoke your session token at any time by clicking **Sign out** in the chat header, which atomically clears your session cookie and closes live streams across all browser tabs.\n\n### Data Protection, Ephemeral Processing & Anonymity\n\n- **Ephemeral Session Processing:** Assistant interactions are evaluated in-memory strictly for real-time guidance during your active session.\n- **Zero Third-Party Training or Data Selling:** A 100% data integrity guarantee is maintained: queries and live messages are never sold, rented, monetized, or fed into public generative model training pools.\n- **No Persistent Tracking:** The assistant functions completely without tracking cookies, behavioral tracking scripts, or persistent fingerprinting.\n- **Active Beta Guardrails:** Automated rate-limiting and input sanitization protect against malicious exploitation while maintaining zero layout shift (`CLS = 0`) across desktop and mobile devices.",
    },
    {
      id: "whatsapp-data-export",
      heading: "7. WhatsApp Recruiter Data Portability & Self-Service Export (GDPR Art. 20)",
      filterMode: "whatsapp",
      order: 7,
      contentMarkdown: "In full compliance with **GDPR Article 20 (Right to Data Portability)** and the **California Consumer Privacy Act (CCPA)**, visitors and recruiters interacting with Gaurav Patil via the official WhatsApp Business channel maintain absolute ownership of their communication records:\n\n- **Instant ZIP Archive:** Typing `/exportmydata` in WhatsApp immediately triggers the server to compile an encrypted in-memory ZIP package containing your complete records with zero wait time.\n- **Visual HTML Log:** Includes a standalone, beautifully styled Dark Luxury HTML transcript featuring verified timestamps, speaker badges, and Gaurav Portfolio branding readable offline on any browser.\n- **GDPR Certificate:** Every export includes an official Data Portability Certificate detailing exact UTC generation timestamps, session identifiers, compliance guarantees, and SHA-256 integrity verification.\n\n### How to Export Your WhatsApp Chat Data (2 Simple Steps)\n\n1. In your active WhatsApp conversation with Gaurav Patil, send: `/exportmydata` (or `/export`).\n2. The automated system will immediately confirm with a generation notice, followed by a cryptographically signed HMAC download link (strictly valid for 10 minutes). Tap the link to download your `.zip` archive directly to your device.\n\n### GDPR Article 17: Right to Immediate Erasure (STOP Command)\n\nYou maintain full sovereignty over your information. At any point, simply reply `STOP` to WhatsApp. The server immediately unsubscribes your number and permanently erases all message documents and session data from the database in an atomic transaction.",
    },
    {
      id: "admin-privacy",
      heading: "8. Administrative Subsystem Privacy Governance",
      filterMode: "all",
      order: 8,
      contentMarkdown: "The administrative panel (`/admin/*`) maintains a strictly isolated data governance architecture. Administrative authentication is restricted to authorized Superadmins via Google OAuth 2.0 PKCE. 2FA One-Time Passcodes are stored in salted HMAC-SHA256 hashed representations, and security IP verification challenges operate under an immutable 15-minute TTL. Sign-out triggers a complete 5-step detachment that clears all cookies, tokens, and browser session storage. Detailed administrative privacy protocols are documented in the Administrator Privacy Policy.",
    },
    {
      id: "contact-requests",
      heading: "9. Contact & Data Requests",
      filterMode: "all",
      order: 9,
      contentMarkdown: "For formal privacy inquiries, data deletion requests, or direct professional communication:\n\n- **Direct Professional & Controller Inquiries:** [gaurav@gauravpatil.site](mailto:gaurav@gauravpatil.site) *(Reserved strictly for professional proposals, consulting contracts, and data controller requests)*\n- **General Inquiries:** [hello@gauravpatil.site](mailto:hello@gauravpatil.site)",
    },
  ],
};
