import type {
  HeroDocument,
  BentoCardDocument,
  ProjectDocument,
  TestimonialDocument,
  ClientDocument,
  ExperienceDocument,
  PhaseDocument,
  NavigationDocument,
  CtaDocument,
  FooterDocument,
  SocialLinkDocument,
  SeoDocument,
  AssistantDocument,
  CloudflareSettingsDocument,
  PublicPortfolioProjection,
} from "@/types/portfolio";
import type { LegalDocument } from "@/types/legal";

export const SEED_HERO: HeroDocument = {
  id: "hero_main",
  eyebrow: "Dynamic Web Magic with Next.js",
  headingWords: "Transforming Concepts into Seamless User Experiences",
  description: "Hi! I'm Gaurav, a Next.js Developer based in India.",
  ctaTitle: "Show my work",
  ctaLink: "#projects",
  scrollText: "Scroll Down",
  isPublished: true,
  updatedAt: new Date().toISOString(),
  version: 1,
};

export const SEED_CARDS: BentoCardDocument[] = [
  {
    id: "card_01",
    slotIndex: 1,
    cardType: "collaboration",
    gridSpanVariant: "span_wide",
    visualLayout: "image_bottom",
    title: "I prioritize client collaboration, fostering open communication",
    description: "",
    img: "/b1.svg",
    spareImg: "",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "card_02",
    slotIndex: 2,
    cardType: "globe_timezone",
    gridSpanVariant: "span_default",
    visualLayout: "globe_canvas",
    title: "I'm very flexible with time zone communications",
    description: "",
    img: "",
    spareImg: "",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "card_03",
    slotIndex: 3,
    cardType: "tech_stack",
    gridSpanVariant: "span_default",
    visualLayout: "tech_pills",
    title: "My tech stack",
    description: "I constantly try to improve",
    techStackLeft: ["React.js", "Next.js", "TypeScript"],
    techStackRight: ["TailwindCSS", "Node.js", "Firebase"],
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "card_04",
    slotIndex: 4,
    cardType: "passion",
    gridSpanVariant: "span_default",
    visualLayout: "image_bottom",
    title: "Tech enthusiast with a passion for development.",
    description: "",
    img: "/b4.svg",
    spareImg: "/grid.svg",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "card_05",
    slotIndex: 5,
    cardType: "current_project",
    gridSpanVariant: "span_wide",
    visualLayout: "image_right",
    title: "Currently building a JS Animation library",
    description: "The Inside Scoop",
    img: "/b5.svg",
    spareImg: "/grid.svg",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "card_06",
    slotIndex: 6,
    cardType: "contact_cta",
    gridSpanVariant: "span_default",
    visualLayout: "centered_text",
    title: "Do you want to start a project together?",
    description: "",
    ctaEmail: "hello@gauravpatil.site",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_PROJECTS: ProjectDocument[] = [
  {
    id: "proj_01",
    order: 1,
    title: "3D Solar System Planets to Explore",
    description: "Explore the wonders of our solar system with this captivating 3D simulation of the planets using Three.js.",
    coverImageStoragePath: "/p1.svg",
    coverImage: "/p1.svg",
    iconLists: ["/re.svg", "/tail.svg", "/ts.svg", "/three.svg", "/fm.svg"],
    liveUrl: "https://github.com/AspiringWebGaurav",
    githubUrl: "https://github.com/AspiringWebGaurav",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "proj_02",
    order: 2,
    title: "Yoom - Video Conferencing App",
    description: "Simplify your video conferencing experience with Yoom. Seamlessly connect with colleagues and friends.",
    coverImageStoragePath: "/p2.svg",
    coverImage: "/p2.svg",
    iconLists: ["/next.svg", "/tail.svg", "/ts.svg", "/stream.svg", "/c.svg"],
    liveUrl: "https://github.com/AspiringWebGaurav",
    githubUrl: "https://github.com/AspiringWebGaurav",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "proj_03",
    order: 3,
    title: "AI Image SaaS - Canva Application",
    description: "A REAL Software-as-a-Service app with AI features and a payments and credits system using the latest tech stack.",
    coverImageStoragePath: "/p3.svg",
    coverImage: "/p3.svg",
    iconLists: ["/re.svg", "/tail.svg", "/ts.svg", "/three.svg", "/c.svg"],
    liveUrl: "https://github.com/AspiringWebGaurav",
    githubUrl: "https://github.com/AspiringWebGaurav",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "proj_04",
    order: 4,
    title: "Animated Apple iPhone 3D Website",
    description: "Recreated the Apple iPhone 15 Pro website, combining GSAP animations and Three.js 3D effects..",
    coverImageStoragePath: "/p4.svg",
    coverImage: "/p4.svg",
    iconLists: ["/next.svg", "/tail.svg", "/ts.svg", "/three.svg", "/gsap.svg"],
    liveUrl: "https://github.com/AspiringWebGaurav",
    githubUrl: "https://github.com/AspiringWebGaurav",
    isFeatured: true,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_TESTIMONIALS: TestimonialDocument[] = [
  {
    id: "test_01",
    order: 1,
    quote: "Collaborating with Gaurav was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Gaurav's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Gaurav is the ideal partner.",
    name: "Michael Johnson",
    role: "Director of AlphaStream Technologies",
    company: "AlphaStream",
    avatarStoragePath: "/profile.svg",
    avatarUrl: "/profile.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "test_02",
    order: 2,
    quote: "Collaborating with Gaurav was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Gaurav's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Gaurav is the ideal partner.",
    name: "Michael Johnson",
    role: "Director of AlphaStream Technologies",
    company: "AlphaStream",
    avatarStoragePath: "/profile.svg",
    avatarUrl: "/profile.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "test_03",
    order: 3,
    quote: "Collaborating with Gaurav was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Gaurav's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Gaurav is the ideal partner.",
    name: "Michael Johnson",
    role: "Director of AlphaStream Technologies",
    company: "AlphaStream",
    avatarStoragePath: "/profile.svg",
    avatarUrl: "/profile.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "test_04",
    order: 4,
    quote: "Collaborating with Gaurav was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Gaurav's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Gaurav is the ideal partner.",
    name: "Michael Johnson",
    role: "Director of AlphaStream Technologies",
    company: "AlphaStream",
    avatarStoragePath: "/profile.svg",
    avatarUrl: "/profile.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "test_05",
    order: 5,
    quote: "Collaborating with Gaurav was an absolute pleasure. His professionalism, promptness, and dedication to delivering exceptional results were evident throughout our project. Gaurav's enthusiasm for every facet of development truly stands out. If you're seeking to elevate your website and elevate your brand, Gaurav is the ideal partner.",
    name: "Michael Johnson",
    role: "Director of AlphaStream Technologies",
    company: "AlphaStream",
    avatarStoragePath: "/profile.svg",
    avatarUrl: "/profile.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_CLIENTS: ClientDocument[] = [
  {
    id: "client_01",
    order: 1,
    name: "cloudinary",
    iconStoragePath: "/cloud.svg",
    iconUrl: "/cloud.svg",
    nameImgStoragePath: "/cloudName.svg",
    nameImgUrl: "/cloudName.svg",
    websiteUrl: "https://cloudinary.com",
    logoWidth: 40,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "client_02",
    order: 2,
    name: "appwrite",
    iconStoragePath: "/app.svg",
    iconUrl: "/app.svg",
    nameImgStoragePath: "/appName.svg",
    nameImgUrl: "/appName.svg",
    websiteUrl: "https://appwrite.io",
    logoWidth: 60,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "client_03",
    order: 3,
    name: "HOSTINGER",
    iconStoragePath: "/host.svg",
    iconUrl: "/host.svg",
    nameImgStoragePath: "/hostName.svg",
    nameImgUrl: "/hostName.svg",
    websiteUrl: "https://hostinger.com",
    logoWidth: 60,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "client_04",
    order: 4,
    name: "stream",
    iconStoragePath: "/s.svg",
    iconUrl: "/s.svg",
    nameImgStoragePath: "/streamName.svg",
    nameImgUrl: "/streamName.svg",
    websiteUrl: "https://getstream.io",
    logoWidth: 50,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "client_05",
    order: 5,
    name: "docker.",
    iconStoragePath: "/dock.svg",
    iconUrl: "/dock.svg",
    nameImgStoragePath: "/dockerName.svg",
    nameImgUrl: "/dockerName.svg",
    websiteUrl: "https://docker.com",
    logoWidth: 50,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_EXPERIENCE: ExperienceDocument[] = [
  {
    id: "exp_01",
    order: 1,
    title: "Frontend Engineer Intern",
    description: "Assisted in the development of a web-based platform using React.js, enhancing interactivity.",
    company: "Tech Labs",
    period: "2023 - 2024",
    thumbnailStoragePath: "/exp1.svg",
    thumbnailUrl: "/exp1.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "exp_02",
    order: 2,
    title: "Mobile App Dev - JSM Tech",
    description: "Designed and developed mobile app for both iOS & Android platforms using React Native.",
    company: "JSM Tech",
    period: "2024",
    thumbnailStoragePath: "/exp2.svg",
    thumbnailUrl: "/exp2.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "exp_03",
    order: 3,
    title: "Freelance App Dev Project",
    description: "Led the dev of a mobile app for a client, from initial concept to deployment on app stores.",
    company: "Independent",
    period: "2024 - 2025",
    thumbnailStoragePath: "/exp3.svg",
    thumbnailUrl: "/exp3.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "exp_04",
    order: 4,
    title: "Lead Frontend Developer",
    description: "Developed and maintained user-facing features using modern frontend technologies.",
    company: "Dev Studio",
    period: "2025 - Present",
    thumbnailStoragePath: "/exp4.svg",
    thumbnailUrl: "/exp4.svg",
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_PHASES: PhaseDocument[] = [
  {
    id: "phase_01",
    order: 1,
    phaseBadge: "Phase 1",
    title: "Planning & Strategy",
    description: "We'll collaborate to map out your website's goals, target audience, and key functionalities. We'll discuss things like site structure, navigation, and content requirements.",
    themeColor: "emerald",
    animationSpeed: 5.1,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "phase_02",
    order: 2,
    phaseBadge: "Phase 2",
    title: "Development & Progress Update",
    description: "Once we agree on the plan, I cue my lofi playlist and dive into coding. From initial sketches to polished code, I keep you updated every step of the way.",
    themeColor: "pink",
    animationSpeed: 3.0,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "phase_03",
    order: 3,
    phaseBadge: "Phase 3",
    title: "Development & Launch",
    description: "This is where the magic happens! Based on the approved design, I'll build your website from the ground up, ensuring everything is responsive, performant, and accessible.",
    themeColor: "sky",
    animationSpeed: 3.0,
    isPublished: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_NAVIGATION: NavigationDocument = {
  id: "nav_main",
  items: [
    { id: "nav_about", name: "About", link: "#about", order: 1, isVisible: true },
    { id: "nav_projects", name: "Projects", link: "#projects", order: 2, isVisible: true },
    { id: "nav_testimonials", name: "Testimonials", link: "#testimonials", order: 3, isVisible: true },
    { id: "nav_contact", name: "Contact", link: "#contact", order: 4, isVisible: true },
  ],
  updatedAt: new Date().toISOString(),
  version: 1,
};

export const SEED_CTA: CtaDocument = {
  id: "cta_main",
  headingPrefix: "Ready to take ",
  headingHighlight: "your",
  headingSuffix: " digital presence to the next level?",
  description: "Reach out to me today and let's discuss how I can help you achieve your goals.",
  buttonText: "Let's get in touch",
  isEnabled: true,
  updatedAt: new Date().toISOString(),
  version: 1,
};

export const SEED_FOOTER: FooterDocument = {
  id: "footer_main",
  copyrightName: "Gaurav",
  termsUrl: "/terms",
  privacyUrl: "/privacy",
  updatedAt: new Date().toISOString(),
  version: 1,
};

export const SEED_SOCIAL_LINKS: SocialLinkDocument[] = [
  {
    id: "soc_01",
    order: 1,
    platform: "GitHub",
    url: "https://github.com/AspiringWebGaurav",
    iconType: "preset",
    presetName: "github",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "soc_02",
    order: 2,
    platform: "Twitter",
    url: "https://twitter.com",
    iconType: "preset",
    presetName: "twitter",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
  {
    id: "soc_03",
    order: 3,
    platform: "LinkedIn",
    url: "https://linkedin.com",
    iconType: "preset",
    presetName: "linkedin",
    isPublished: true,
    updatedAt: new Date().toISOString(),
    version: 1,
  },
];

export const SEED_SEO: SeoDocument = {
  id: "seo_main",
  title: "Gaurav's Portfolio",
  description: "Modern, Slick and Minimalist Developer Portfolio",
  canonicalUrl: "https://gauravpatil.site",
  ogImageStoragePath: "",
  ogImageUrl: "",
  keywords: ["Developer", "Portfolio", "Frontend", "Next.js", "React", "TypeScript"],
  author: "Gaurav Patil",
  twitterHandle: "@gauravpatil",
  updatedAt: new Date().toISOString(),
  version: 1,
};

export const SEED_ASSISTANT: AssistantDocument = {
  id: "assistant_main",
  isEnabled: true,
  assistantName: "Gaurav Assistant",
  avatarUrl: "",
  positionMode: "fixed",
  updatedAt: new Date().toISOString(),
  version: 1,
};

export const SEED_CLOUDFLARE: CloudflareSettingsDocument = {
  id: "cloudflare_main",
  isSimulatedDowntime: false,
  siteKey: "0x4AAAAAAEilFWDvwBZ3NPSK",
  maxRetryAttempts: 2,
  circuitBreakerEnabled: true,
  fallbackEmailGateway: "no-reply@gauravpatil.site",
  updatedAt: new Date().toISOString(),
  version: 1,
};

export const SEED_PORTFOLIO_PROJECTION: PublicPortfolioProjection = {
  navigation: SEED_NAVIGATION.items,
  hero: SEED_HERO,
  cards: SEED_CARDS,
  projects: SEED_PROJECTS,
  testimonials: SEED_TESTIMONIALS,
  clients: SEED_CLIENTS,
  experience: SEED_EXPERIENCE,
  phases: SEED_PHASES,
  cta: SEED_CTA,
  footer: SEED_FOOTER,
  socialLinks: SEED_SOCIAL_LINKS,
  seo: SEED_SEO,
  assistant: SEED_ASSISTANT,
  cloudflare: SEED_CLOUDFLARE,
};

export const SEED_TERMS_DOCUMENT: LegalDocument = {
  id: "terms_active",
  docType: "TERMS",
  title: "Terms of Service",
  publishedVersion: "0.0.1",
  publishedAt: "2026-01-01T00:00:00.000Z",
  effectiveDate: "January 1, 2026",
  lastUpdatedDate: "August 29, 2026",
  jurisdiction: "Standard Global",
  version: 1,
  updatedAt: new Date().toISOString(),
  sections: [
    {
      id: "acceptance",
      heading: "1. Acceptance of Terms & Accessibility Commitment",
      filterMode: "all",
      order: 1,
      contentMarkdown: "By accessing, browsing, submitting inquiries, using authenticated services, or otherwise interacting with **Gaurav Portfolio**, you acknowledge and agree to be bound by these Terms of Service and all applicable policies. This platform commits to a strict **Mobile-First 10/10 Production Standard**, ensuring zero horizontal overflow, fluid typography, touch-ergonomic 44px hit targets, accessible reduced-motion fallbacks, and single-view contact workflows across all modern smartphones, tablets, and desktop workstations. If you do not agree with any provision, you may discontinue viewing or utilizing this platform.",
    },
    {
      id: "anonymity",
      heading: "2. Right to Confidential & Anonymous Communication",
      filterMode: "contact",
      order: 2,
      contentMarkdown: "Users and prospective partners are welcome to initiate contact anonymously:\n\n- **Confidential Inquiries:** Submitting an inquiry with the default \"Anonymous / Confidential\" role is fully permitted and legally respected as preliminary communication.\n- **Non-Disclosure Friendly:** Mutual non-disclosure agreements (NDAs) can be executed upon request prior to exchanging proprietary project details.",
    },
    {
      id: "ip",
      heading: "3. Intellectual Property & Engineering Architecture",
      filterMode: "all",
      order: 3,
      contentMarkdown: "All original visual design systems, dark luxury glassmorphic layouts, Three.js 3D Globe implementations, and full-stack software architectures showcased on this platform are the intellectual property of **Gaurav Patil**. Client deliverables and bespoke software engineering codebases are transferred strictly per individual written engagement agreements upon milestone completion.",
    },
    {
      id: "abuse-mitigation",
      heading: "4. Automated Abuse Mitigation & Cloudflare Verification",
      filterMode: "contact",
      order: 4,
      contentMarkdown: "To maintain high uptime and system integrity, public mutation endpoints (such as the contact form) are protected by **Cloudflare Turnstile**. Automated scraping, malicious payload injection, bot spam, and denial-of-service attempts are strictly prohibited and actively mitigated.",
    },
    {
      id: "email-standards",
      heading: "5. Transactional Communication Standards & Mandatory Legal Update Announcements",
      filterMode: "contact",
      order: 5,
      contentMarkdown: "All transactional emails, contact receipts, security alerts, and mandatory policy notices are dispatched from the authenticated server domain `gauravpatil.site` via Brevo API. Official sender identities include `hello@gauravpatil.site` (inquiries and auto-replies), `security@gauravpatil.site` (authentication alerts and audit logs), `help@gauravpatil.site` (support), and `no-reply@gauravpatil.site` (system OTPs and automated legal announcements). A strict zero-spam guarantee is maintained: submitted contact emails are never enrolled in promotional marketing sequences.\n\n### Mandatory Legal & Policy Update Announcement Notice\n\n- **Automatic Registration for Policy Updates:** Submitting an email address through any service of this portfolio — including Contact Form inquiries, Live Chat email OTP authentication, support requests, or direct communications — registers that address to receive mandatory policy, legal, and security announcements in accordance with your acceptance of use.\n- **Mandatory Non-Marketing Announcements:** When material updates are made to the public Terms of Service, Privacy Policy, or critical security procedures, automated informational notices are broadcast directly from `no-reply@gauravpatil.site` or `security@gauravpatil.site`. These communications are strictly non-commercial, transactional legal disclosures and contain zero marketing or promotional sequences.\n- **No Unsubscribe & Immunity from Automated Client-Level Unsubscribe:** Because legal update announcements are mandatory contractual disclosures required to maintain operational and legal transparency for all users who have interacted with Gaurav Portfolio or its authenticated services, **no unsubscribe or opt-out option is provided**. Even if automated email client features (such as Google/Gmail's automatic \"Unsubscribe\" header or client-level spam filters) are invoked, you acknowledge and agree that you will continue to receive mandatory legal, policy, and security notices as per this policy and your acceptance of use.",
    },
    {
      id: "assistant-terms",
      heading: "6. Personal Assistant (Beta) Operational Terms & AI Disclaimer",
      filterMode: "assistant",
      order: 6,
      contentMarkdown: "### Purpose & Scope of Gaurav Assistant & Live Chat\n\nThe Personal Assistant and Live Chat system are engineered to provide an interactive, personal communication channel with Gaurav Patil. It provides direct, automated insights into engineering benchmarks, architecture patterns, and project deliverables, while facilitating immediate 1-to-1 live communication.\n\n### Live Chat Real-Time Dispatch & Notification Architecture\n\nWhen you initiate a conversation through **Live Chat with Gaurav**, the backend operates a hybrid real-time communication pipeline:\n\n- **Active Online Streaming:** If Gaurav is actively online and connected to the session, incoming messages arrive instantly in real-time.\n- **Automated Inbox Dispatch:** If Gaurav is away or offline, the server instantaneously generates and dispatches an automated lead notification directly to Gaurav's private inbox containing your verified sender details and full message transcript with 1-click direct response routing.\n- **Single-Use 6-Digit Email Verification:** To eliminate spam and protect system resources, access to Live Chat requires a single-use 6-digit OTP code dispatched exclusively from `no-reply@gauravpatil.site`. Verification codes expire in 5 minutes.\n- **4-Hour Active Session Token:** Once verified, an encrypted session remains active for 4 hours. You may close and reopen the chat window anytime within this window without re-authenticating. Visitors may explicitly terminate their session at any time using the **Sign out** button in the top-right header.\n\n### Official Verified Senders & Support Pipeline\n\nAll communications, support tickets, and contact verification flows originate exclusively from the authenticated domain `gauravpatil.site`:\n\n- `hello@gauravpatil.site` — General portfolio inquiries, recruiter outreach, and direct developer contact.\n- `help@gauravpatil.site` — Assistant technical support, bug reports, and portfolio navigation guidance.\n- `security@gauravpatil.site` — Security notifications, 2FA OTP codes, and vulnerability disclosure reports.\n- `no-reply@gauravpatil.site` — Automated Live Chat OTP passcodes, system receipts, and non-interactive alerts.\n\n### AI Accuracy Disclaimer & Acceptable Use\n\n- **Generative Limitations:** While tuned for accuracy, automated assistant responses may occasionally produce incomplete or summarized statements. Official portfolio source code and direct communication with Gaurav remain authoritative benchmarks.\n- **Acceptable Use:** Visitors agree not to attempt prompt-injections, reverse-engineer underlying system prompts, extract internal configuration, or send abusive payloads.\n- **Continuous Beta Evolution:** The assistant is under active development and may undergo live feature updates or brief maintenance windows without notice.",
    },
    {
      id: "whatsapp-terms",
      heading: "7. WhatsApp Recruiter & Visitor Communication Channel",
      filterMode: "whatsapp",
      order: 7,
      contentMarkdown: "Gaurav Portfolio provides an official Meta WhatsApp Business Cloud API integration allowing recruiters, hiring managers, and prospective clients to connect directly with Gaurav Patil. Use of this channel is subject to the following terms:\n\n- **Authorized Professional Scope:** This WhatsApp channel is exclusively intended for professional recruitment discussions, job opportunities, engineering inquiries, and technical collaboration proposals. Promotional spam, harassment, or unsolicited marketing is strictly prohibited.\n- **Message Quota & Anti-Spam Safeguards:** To prevent spam and protect direct communication channels, sessions are allocated up to 3 direct inquiry message slots. Messages are delivered instantaneously to Gaurav Patil in real time with 1-click email response triggers.\n- **Unsubscribe & Immediate Data Erasure:** You may opt out at any time by replying `STOP`. Replying STOP immediately unsubscribes your number and permanently erases your conversation history from the database (GDPR Right to Erasure). You can resume anytime by replying `START`.\n- **Data Portability & Self-Service Export:** Under GDPR Article 20, you retain full ownership of your conversation records. You can type `/exportmydata` anytime in WhatsApp to instantly receive a cryptographically signed ZIP archive with your complete records (links are strictly time-limited to 10 minutes for privacy).",
    },
    {
      id: "admin-governance",
      heading: "8. Administrative Subsystem Isolation & 2FA Governance",
      filterMode: "all",
      order: 8,
      contentMarkdown: "The administrative panel (`/admin/*`) is an isolated workspace strictly restricted to authorized Superadmins. Administrative access requires Google OAuth 2.0 PKCE, salted HMAC-SHA256 Two-Factor Authentication (OTP), and zero-lockout IP security verification. Administrative access and data operations are governed separately under the Administrator Terms of Service.",
    },
    {
      id: "liability",
      heading: "9. Limitation of Liability & Disclaimers",
      filterMode: "all",
      order: 9,
      contentMarkdown: "This website and its demonstrative artifacts are provided on an \"as is\" and \"as available\" basis. In no event shall Gaurav Patil be liable for indirect, incidental, or consequential damages resulting from the use of this website.",
    },
    {
      id: "legal-contact",
      heading: "10. Inquiries & Legal Notices",
      filterMode: "all",
      order: 10,
      contentMarkdown: "For legal inquiries, contract proposals, or engagement agreements:\n\nEmail: [hello@gauravpatil.site](mailto:hello@gauravpatil.site)",
    },
  ],
};

export const SEED_PRIVACY_DOCUMENT: LegalDocument = {
  id: "privacy_active",
  docType: "PRIVACY",
  title: "Privacy Policy",
  publishedVersion: "0.0.1",
  publishedAt: "2026-01-01T00:00:00.000Z",
  effectiveDate: "January 1, 2026",
  lastUpdatedDate: "August 29, 2026",
  jurisdiction: "Privacy-First",
  version: 1,
  updatedAt: new Date().toISOString(),
  sections: [
    {
      id: "overview",
      heading: "1. Overview & Privacy-First Philosophy",
      filterMode: "all",
      order: 1,
      contentMarkdown: "Your privacy, autonomy, and security are non-negotiable. This Privacy Policy governs how data is handled across **Gaurav Portfolio**. The architecture operates on strict data minimization principles: only the minimum information necessary to facilitate professional communication is collected, with zero third-party data tracking, zero cookie profiling, and zero monetization of personal information.",
    },
    {
      id: "anonymity",
      heading: "2. Absolute Right to Anonymity & Confidential Inquiries",
      filterMode: "contact",
      order: 2,
      contentMarkdown: "Every visitor and prospective collaborator has the full, unrestricted right to maintain complete anonymity:\n\n- **Default Anonymous Role:** The contact form defaults to the \"Anonymous / Confidential\" identity to ensure no visitor is pressured into declaring a specific role.\n- **Pseudonyms & Private Relays:** You may submit inquiries using an alias, pseudonym, or privacy-relayed email address (such as Apple Relay or SimpleLogin).\n- **Zero Telemetry Correlation:** Inbound contact messages are strictly segregated from user-agent fingerprints and external analytics data.",
    },
    {
      id: "turnstile",
      heading: "3. Bot Mitigation & Ephemeral Cloudflare Turnstile Evaluation",
      filterMode: "contact",
      order: 3,
      contentMarkdown: "To protect public endpoints against automated spam and DDoS attacks, the system utilizes **Cloudflare Turnstile**:\n\n- **Cookie-Free Evaluation:** Turnstile evaluates browser telemetry ephemerally during submission without setting persistent cross-site tracking cookies.\n- **Server-Side Token Validation:** Tokens are validated instantaneously via server-to-server TLS calls and discarded immediately following verification.",
    },
    {
      id: "brevo",
      heading: "4. Transactional Communications & Brevo Delivery Gateway",
      filterMode: "contact",
      order: 4,
      contentMarkdown: "All transactional communications, verification passcodes, and mandatory legal announcements are routed through an enterprise Brevo server pipeline:\n\n- **Authenticated Domain:** Official communications originate strictly from the verified primary identity `gauravpatil.site`.\n- **Official Senders:**\n  - `hello@gauravpatil.site` (Direct contact & automated receipts)\n  - `security@gauravpatil.site` (Security alerts, authentication verification & push audit logs)\n  - `help@gauravpatil.site` (Support & assistance)\n  - `no-reply@gauravpatil.site` (System OTPs & mandatory legal update announcements)\n- **Strict Non-Marketing Standard:** Submitting an inquiry or authenticating will never enroll you in promotional campaigns or marketing distributions.\n\n### Mandatory Legal Update Broadcasts & Strict No-Unsubscribe Standard\n\nEmail addresses provided through Contact Form submissions, Assistant/Live Chat OTP authentication, or direct inquiries are retained securely in cloud databases. These addresses receive mandatory service announcements whenever the public Terms of Service or Privacy Policy are amended. Because these notices represent vital legal disclosures required for platform transparency and governance (and never commercial marketing), they do not include marketing unsubscribe links and cannot be opted out of, even through third-party automated email client features (such as Google/Gmail automatic 1-click unsubscribe headers).",
    },
    {
      id: "data-rights",
      heading: "5. Data Security, Storage & Deletion Rights",
      filterMode: "all",
      order: 5,
      contentMarkdown: "Inquiries are stored in encrypted cloud databases (Firebase Firestore / Realtime Database in region `asia-southeast1`) with atomic lead tracking. You retain the right under GDPR, CCPA, and international privacy standards to:\n\n- Request a copy of any communication history associated with your email.\n- Request permanent, atomic deletion of all submitted contact records and message drafts.",
    },
    {
      id: "assistant-privacy",
      heading: "6. Personal Assistant (Beta) & AI Safety Architecture",
      filterMode: "assistant",
      order: 6,
      contentMarkdown: "### Why Gaurav Assistant Was Created\n\nThe Personal Assistant was conceived and engineered as an **intelligent interactive portfolio navigator** designed to elevate how recruiters, hiring managers, engineering leaders, and potential clients explore Gaurav Patil's work. Instead of manually parsing static resume bullets, visitors can receive real-time answers concerning deep case studies, technical specializations, engineering philosophy, and live architectural demonstrations.\n\n### Custom Mail Domain Support & Verified Communication Channels\n\nAll visitor interactions, assistant support inquiries, and transactional communications are backed by a dedicated, enterprise-grade Brevo email delivery pipeline configured with strict **SPF, DKIM, and DMARC** authentication records. Official communication originating from this portfolio is bound to the primary authenticated domain `gauravpatil.site`:\n\n- `hello@gauravpatil.site` — Direct portfolio contact, visitor inquiries, developer collaboration, and automated inquiry receipts.\n- `help@gauravpatil.site` — Assistant technical assistance, bug reports, user feedback, and portfolio navigation support.\n- `security@gauravpatil.site` — Security disclosures, vulnerability reports, 2FA OTP codes, and authentication alerts.\n- `no-reply@gauravpatil.site` — Non-interactive automated notifications, system passcodes, and security verifications only.\n\n### Live Chat Notification Privacy & 4-Hour Session Security\n\n- **Direct Message Routing:** When you send a message in Live Chat, it is streamed immediately if Gaurav is connected. When away, the automated system triggers an instantaneous notification email to Gaurav's personal inbox with your message transcript and 1-click reply routing.\n- **Zero Plaintext OTP Storage:** 6-digit verification codes are hashed using salted HMAC-SHA256 before storage and destroyed immediately upon successful authentication or after 5 minutes.\n- **Encrypted 4-Hour Session Token:** Verified sessions are stored in an encrypted `httpOnly`, `SameSite=Lax` cookie valid for 4 hours. You can close and return to the portfolio anytime during this period without re-verifying.\n- **1-Click Sign-Out & Detachment:** You may revoke your session token at any time by clicking **Sign out** in the chat header, which atomically clears your session cookie and closes live streams across all browser tabs.\n\n### Data Protection, Ephemeral Processing & Anonymity\n\n- **Ephemeral Session Processing:** Assistant interactions are evaluated in-memory strictly for real-time guidance during your active session.\n- **Zero Third-Party Training or Data Selling:** A 100% data integrity guarantee is maintained: queries and live messages are never sold, rented, monetized, or fed into public generative model training pools.\n- **No Persistent Tracking:** The assistant functions completely without tracking cookies, behavioral tracking scripts, or persistent fingerprinting.\n- **Active Beta Guardrails:** Automated rate-limiting and input sanitization protect against malicious exploitation while maintaining zero layout shift (`CLS = 0`) across desktop and mobile devices.",
    },
    {
      id: "whatsapp-data-export",
      heading: "7. WhatsApp Recruiter Data Portability & Self-Service Export (GDPR Art. 20)",
      filterMode: "whatsapp",
      order: 7,
      contentMarkdown: "In full compliance with **GDPR Article 20 (Right to Data Portability)** and the **California Consumer Privacy Act (CCPA)**, visitors and recruiters interacting with Gaurav Patil via the official WhatsApp Business channel maintain absolute ownership of their communication records:\n\n- **Instant ZIP Archive:** Typing `/exportmydata` in WhatsApp immediately triggers the server to compile an encrypted in-memory ZIP package containing your complete records with zero wait time.\n- **Visual HTML Log:** Includes a standalone, beautifully styled Dark Luxury HTML transcript featuring verified timestamps, speaker badges, and Gaurav Portfolio branding readable offline on any browser.\n- **GDPR Certificate:** Every export includes an official Data Portability Certificate detailing exact UTC generation timestamps, session identifiers, compliance guarantees, and SHA-256 integrity verification.\n\n### How to Export Your WhatsApp Chat Data (2 Simple Steps)\n\n1. In your active WhatsApp conversation with Gaurav Patil, send: `/exportmydata` (or `/export`).\n2. The automated system will immediately confirm with a generation notice, followed by a cryptographically signed HMAC download link (strictly valid for 10 minutes). Tap the link to download your `.zip` archive directly to your device.\n\n### GDPR Article 17: Right to Immediate Erasure (STOP Command)\n\nYou maintain full sovereignty over your information. At any point, simply reply `STOP` to WhatsApp. The server immediately unsubscribes your number and permanently erases all message documents and session data from the database in an atomic transaction.",
    },
    {
      id: "admin-privacy",
      heading: "8. Administrative Subsystem Privacy Governance",
      filterMode: "all",
      order: 8,
      contentMarkdown: "The administrative panel (`/admin/*`) maintains a strictly isolated data governance architecture. Administrative authentication is restricted to authorized Superadmins via Google OAuth 2.0 PKCE. 2FA One-Time Passcodes are stored in salted HMAC-SHA256 hashed representations, and security IP verification challenges operate under an immutable 15-minute TTL. Sign-out triggers a complete 5-step detachment that clears all cookies, tokens, and browser session storage. Detailed administrative privacy protocols are documented in the Administrator Privacy Policy.",
    },
    {
      id: "contact-requests",
      heading: "9. Contact & Data Requests",
      filterMode: "all",
      order: 9,
      contentMarkdown: "For any privacy inquiries, data deletion requests, or security disclosures, reach out directly to:\n\nEmail: [hello@gauravpatil.site](mailto:hello@gauravpatil.site)",
    },
  ],
};
