// Bubble Management System Types

export interface BubbleMessage {
  id: string;
  sessionId: string;
  role: 'visitor' | 'admin';
  content: string;
  timestamp: Date;
  read: boolean;
  delivered: boolean;
  visitorEmail?: string;
  readAt?: Date;
  deliveredAt?: Date;
}

export interface BubbleSession {
  id: string; // UUID generated by backend (device_uuid)
  mask: string; // Public mask from UUID-sync system (device_**********)
  visitorEmail?: string;
  startedAt: Date;
  lastActive: Date;
  messageCount: number;
  unreadAdminReplies: number;
  unreadVisitorMessages: number;
  hasUnreadTooltip: boolean;
  visitorTyping?: boolean;
  adminTyping?: boolean;
  visitorLastSeen?: Date;
  adminLastSeen?: Date;
  visitorOnline?: boolean;
  adminOnline?: boolean;
  deletedAt?: Date | null;
}

export interface PredefinedQuestion {
  id: string;
  question: string;
  answer: string;
  order: number;
  active: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface ResumeVersion {
  id: string;
  fileName: string;
  fileUrl: string;
  uploadedAt: Date;
  version: number;
  isCurrent: boolean;
  fileSize: number;
  deletedAt?: Date;
}

export interface TooltipEvent {
  id: string;
  sessionId: string;
  triggeredAt: Date;
  readAt?: Date;
  messageId: string;
  visitorEmail?: string;
}

export interface BubbleSettings {
  id: string;
  bubbleText: string;
  welcomeMessage: string;
  quickActionsTitle: string;
  predefinedQuestionsTitle: string;
  tooltipDelay: number; // milliseconds
  bubbleColor: string;
  bubblePosition: 'bottom-right' | 'bottom-left';
  enableTooltip: boolean;
  chatPlaceholder: string;
  updatedAt: Date;
}

export interface BubbleStats {
  totalVisitors: number;
  activeSessions: number;
  unreadMessages: number;
  tooltipTriggers: number;
  messagesThisWeek: number;
  averageResponseTime: number;
}

export interface ChatMessage {
  role: 'visitor' | 'admin';
  content: string;
  timestamp: Date;
}

export interface MessageHistory {
  messages: BubbleMessage[];
  hasMore: boolean;
  totalCount: number;
}
